---
golang/go1.3.1.linux-amd64.tar.gz:
  object_id: deda46b4-5a57-428e-b6dc-42e30a4b67b1
  sha: !binary |-
    M2FmMDExY2MxOWIyMWM3MTgwZjI2MDRmZDg1ZmJjNGRkZGU5NzE0Mw==
  size: 51930765
iptables/iptables-1.4.21.tar.bz2:
  object_id: 66b91b2f-bbd2-42f7-af53-286e7cefa63a
  sha: !binary |-
    ODVkNDE2MDUzNzU0NmEyM2E3ZTQyYmMyNmRkN2VlNjJhMGVkZTRjOA==
  size: 547439
shadow/shadow-4.2.1.tar.gz:
  object_id: aea45a48-df25-424e-9ddb-bbcc89ab3cbb
  sha: !binary |-
    MWQyMDU0MTg4NjNkZDAyYjJiOGFmMGZhNzhmY2NlNWQ3Yzg0OGQxZg==
  size: 3686676
