---
packages:
- name: garden-linux
  version: !binary |-
    MDM3ZDRiNzgzYWMzZjI4NWU2MzVjNDdhZDk4ZWNiODRjYmU1MGFmNg==
  fingerprint: !binary |-
    MDM3ZDRiNzgzYWMzZjI4NWU2MzVjNDdhZDk4ZWNiODRjYmU1MGFmNg==
  sha1: !binary |-
    ZThhMzJlMTkxNzkwZmZhMjI3YTMzYmI2NTgwY2FhYjJkNjRkNTExZA==
  dependencies:
  - btrfs-progs
  - golang_1.4
- name: btrfs-progs
  version: !binary |-
    ODc4NTgzOTMyYmQ4NzY5ODIxYTk0N2MyMTA0OTU5OGE2YWFlMmMxMg==
  fingerprint: !binary |-
    ODc4NTgzOTMyYmQ4NzY5ODIxYTk0N2MyMTA0OTU5OGE2YWFlMmMxMg==
  sha1: !binary |-
    MTFkMmYxZGIwMGM5YzEwOGVkZmUwNjA1MmRhZGE2NDEzMjRlZmJjYg==
  dependencies: []
- name: busybox
  version: !binary |-
    MTU5M2M0MWJlYjU3YzEyZDdmMmI4MmRmZjYxYjQ3ZDRkMTE5OTEzZA==
  fingerprint: !binary |-
    MTU5M2M0MWJlYjU3YzEyZDdmMmI4MmRmZjYxYjQ3ZDRkMTE5OTEzZA==
  sha1: !binary |-
    YzQ2YmVhOTU4NWRlY2M1NGU3MDUyZWZjMjdjMTM4ZDdiNjE4ZmZhZQ==
  dependencies: []
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    OTgzNDVlNzJmZDk3OTg0YjhjMmExYTQ4NWI5OTg4ZjIwN2RjZTYwZA==
  dependencies: []
- name: golang_1.4
  version: !binary |-
    ZjU3ZGRiYzhkNTVkN2EwZjA4Nzc1YmY3NmJiNmEyN2RjOThjN2VhNw==
  fingerprint: !binary |-
    ZjU3ZGRiYzhkNTVkN2EwZjA4Nzc1YmY3NmJiNmEyN2RjOThjN2VhNw==
  sha1: !binary |-
    ZDIxY2Y4NjhmODNjM2U0M2FjNGJhZTc1YzIxMDQxNzgzZmYzYjE1OQ==
  dependencies: []
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    ZTVlYjM4YmZhOGYzYzgxODA4NmJkNDE2ZmRlYzE0ZjlmYjBiNzEzMQ==
  dependencies: []
jobs:
- name: garden
  version: !binary |-
    NDI2MDE5YTg3OWYwYzNhMzI2YmE4NjU3MzIwMjM4NDBhMmRjYzMxZg==
  fingerprint: !binary |-
    NDI2MDE5YTg3OWYwYzNhMzI2YmE4NjU3MzIwMjM4NDBhMmRjYzMxZg==
  sha1: !binary |-
    NTNjOWM2MTJkNjI5MjU3OTM0ODM1NDEzODQzZDIzNzYyZDY4Y2ZkOA==
license:
  version: !binary |-
    NWQ4ZWU4MWRjOWU2MTJjMGVlZmNmMzllOWVmYWU2NmQyZmFkMmE5OQ==
  fingerprint: !binary |-
    NWQ4ZWU4MWRjOWU2MTJjMGVlZmNmMzllOWVmYWU2NmQyZmFkMmE5OQ==
  sha1: !binary |-
    NjYwNDFmYjdkYTRlZTBhYWI1OWFlOWY0YjRlN2ZiMDdkYjdmNjE4OQ==
commit_hash: b5efde0f
uncommitted_changes: false
name: garden-linux
version: 0.273.0
