---
packages:
- name: btrfs-progs
  version: !binary |-
    NzE4ODljNDM3YmUxMTM3Yjk4YWEwOTRhNTJlNjY0Y2ZlOGUzNmNkMw==
  fingerprint: !binary |-
    NzE4ODljNDM3YmUxMTM3Yjk4YWEwOTRhNTJlNjY0Y2ZlOGUzNmNkMw==
  sha1: !binary |-
    MDA1MzlhNzY0NzJmYTc0YmJkNjE2Zjg1YzExMGU5YjViNTc1MjQ1YQ==
  dependencies: []
- name: busybox
  version: !binary |-
    MTU5M2M0MWJlYjU3YzEyZDdmMmI4MmRmZjYxYjQ3ZDRkMTE5OTEzZA==
  fingerprint: !binary |-
    MTU5M2M0MWJlYjU3YzEyZDdmMmI4MmRmZjYxYjQ3ZDRkMTE5OTEzZA==
  sha1: !binary |-
    YzQ2YmVhOTU4NWRlY2M1NGU3MDUyZWZjMjdjMTM4ZDdiNjE4ZmZhZQ==
  dependencies: []
- name: garden-linux
  version: !binary |-
    MGJhYjNlYzhiMDlhMjAyNjg2M2IwMmZhOTc0MmM5Y2RiMmNlYjdhMA==
  fingerprint: !binary |-
    MGJhYjNlYzhiMDlhMjAyNjg2M2IwMmZhOTc0MmM5Y2RiMmNlYjdhMA==
  sha1: !binary |-
    ZTYxY2ZmMDE3YTk1ZDMyYzY2MjEzNzM5OWQ0ZGU4YTAyNjRiZWRiYw==
  dependencies:
  - btrfs-progs
  - golang_1.4
- name: golang_1.4
  version: !binary |-
    ZjU3ZGRiYzhkNTVkN2EwZjA4Nzc1YmY3NmJiNmEyN2RjOThjN2VhNw==
  fingerprint: !binary |-
    ZjU3ZGRiYzhkNTVkN2EwZjA4Nzc1YmY3NmJiNmEyN2RjOThjN2VhNw==
  sha1: !binary |-
    ZDIxY2Y4NjhmODNjM2U0M2FjNGJhZTc1YzIxMDQxNzgzZmYzYjE1OQ==
  dependencies: []
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    OTgzNDVlNzJmZDk3OTg0YjhjMmExYTQ4NWI5OTg4ZjIwN2RjZTYwZA==
  dependencies: []
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    ZTVlYjM4YmZhOGYzYzgxODA4NmJkNDE2ZmRlYzE0ZjlmYjBiNzEzMQ==
  dependencies: []
jobs:
- name: garden
  version: !binary |-
    ZTk2ZjY0MmE5ZTU4OTkzMjZmNTM4ZTVhMzhlMzI1YmYxNmM4ZDI0Zg==
  fingerprint: !binary |-
    ZTk2ZjY0MmE5ZTU4OTkzMjZmNTM4ZTVhMzhlMzI1YmYxNmM4ZDI0Zg==
  sha1: !binary |-
    ZmE3YWFiNDczNzk1Y2E1YTU0NjliZmU1ZThhZTRhM2Q3YWE4YTIwZA==
license:
  version: !binary |-
    NWQ4ZWU4MWRjOWU2MTJjMGVlZmNmMzllOWVmYWU2NmQyZmFkMmE5OQ==
  fingerprint: !binary |-
    NWQ4ZWU4MWRjOWU2MTJjMGVlZmNmMzllOWVmYWU2NmQyZmFkMmE5OQ==
  sha1: !binary |-
    NjYwNDFmYjdkYTRlZTBhYWI1OWFlOWY0YjRlN2ZiMDdkYjdmNjE4OQ==
commit_hash: 71c75bdb
uncommitted_changes: false
name: garden-linux
version: 0.302.0
