---
packages:
- name: iptables
  version: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  fingerprint: !binary |-
    NzIyNmQzMTFlOTBmNDliMDUyODdlNzlmMzM5NTgxYTFkZTllYTgyZQ==
  sha1: !binary |-
    OTgzNDVlNzJmZDk3OTg0YjhjMmExYTQ4NWI5OTg4ZjIwN2RjZTYwZA==
  dependencies: []
- name: golang_1.3
  version: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  fingerprint: !binary |-
    ZTRiNjViY2I0NzhkOWJlYTFmOWM5MjA0MjM0NjUzOTcxMzU1MWE0YQ==
  sha1: !binary |-
    ODFlMjBjZmUxYzUxOTkxMDI3NzM0NTg4ODZlNThjMTdlY2QxMzY3NA==
  dependencies: []
- name: busybox
  version: !binary |-
    MTU5M2M0MWJlYjU3YzEyZDdmMmI4MmRmZjYxYjQ3ZDRkMTE5OTEzZA==
  fingerprint: !binary |-
    MTU5M2M0MWJlYjU3YzEyZDdmMmI4MmRmZjYxYjQ3ZDRkMTE5OTEzZA==
  sha1: !binary |-
    YzQ2YmVhOTU4NWRlY2M1NGU3MDUyZWZjMjdjMTM4ZDdiNjE4ZmZhZQ==
  dependencies: []
- name: shadow
  version: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  fingerprint: !binary |-
    ZmZkMTc0MWJkOWUwYTE3NmU2N2M2MWVmNzBjZDBlZDc2YjBlYzI4NQ==
  sha1: !binary |-
    ZTVlYjM4YmZhOGYzYzgxODA4NmJkNDE2ZmRlYzE0ZjlmYjBiNzEzMQ==
  dependencies: []
- name: garden-linux
  version: !binary |-
    NWJkODZlNjhlMzI4Mjk1MjAwMDIzNTFjOTU0ZjVlZjI0ZGUzMjE1ZA==
  fingerprint: !binary |-
    NWJkODZlNjhlMzI4Mjk1MjAwMDIzNTFjOTU0ZjVlZjI0ZGUzMjE1ZA==
  sha1: !binary |-
    MjVhNTNlY2ZjYTlhN2QxNTczYjJhNjJkNTkzZTI5ODkzMjE4YmRmNQ==
  dependencies:
  - golang_1.3
jobs:
- name: garden
  version: !binary |-
    NzliZjMwYzRhZDNhNDVlYjg2ZTM3ODdjNWU2YzFmYzViYzBlMzExNA==
  fingerprint: !binary |-
    NzliZjMwYzRhZDNhNDVlYjg2ZTM3ODdjNWU2YzFmYzViYzBlMzExNA==
  sha1: !binary |-
    ZDY5ZmJiOTYwZDFhYTliN2QyMDI2ZjhkNTZiNDBlYTAwYTBjOTMyOQ==
license:
  version: !binary |-
    NWQ4ZWU4MWRjOWU2MTJjMGVlZmNmMzllOWVmYWU2NmQyZmFkMmE5OQ==
  fingerprint: !binary |-
    NWQ4ZWU4MWRjOWU2MTJjMGVlZmNmMzllOWVmYWU2NmQyZmFkMmE5OQ==
  sha1: !binary |-
    NjYwNDFmYjdkYTRlZTBhYWI1OWFlOWY0YjRlN2ZiMDdkYjdmNjE4OQ==
commit_hash: ef31dc6d
uncommitted_changes: true
name: garden-linux
version: 0.184.0
